dict_answers = {
    'Como o programa faz previsões?' : '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                        <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                                        p, li { white-space: pre-wrap; }
                                        </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;">
                                        <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">Como o programa faz previsões?</span></p>
                                        <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">As previsões do programa são feitas utilizando o módulo </span><a href="https://facebook.github.io/prophet/docs/quick_start.html"><span style=" font-size:12pt; font-style:italic; text-decoration: underline; color:#0000ff;">fbprophet</span></a><span style=" font-size:12pt; font-style:italic;">, </span><span style=" font-size:12pt;">criado pelo Facebook para as linguagens </span><span style=" font-size:12pt; font-style:italic;">Python </span><span style=" font-size:12pt;">e </span><span style=" font-size:12pt; font-style:italic;">R</span><span style=" font-size:12pt;"> visando realizar previsões de séries temporais. Os modelos preditivos criados no módulo têm diferentes formas de computar tendências e sazonalidades, bem como comportam eventos específicos (por exemplo, feriados) em que há alterações na série diferentes da norma.</span></p>
                                        <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">O </span><span style=" font-size:12pt; font-style:italic;">Prophet</span><span style=" font-size:12pt;"> considera a série de dados contendo três componentes: </span><span style=" font-size:12pt; text-decoration: underline;">Tendência</span><span style=" font-size:12pt;">, </span><span style=" font-size:12pt; text-decoration: underline;">Sazonalidade</span><span style=" font-size:12pt;"> e um </span><span style=" font-size:12pt; text-decoration: underline;">Resíduo</span><span style=" font-size:12pt;">. A relação entre estes pode ser aditiva ou multiplicativa. No programa de análise de dados da Covid-19, o usuário pode selecionar qual será utilizada.</span></p>
                                        <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Para mais informações:</span></p>
                                        <ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;"><li style=" font-size:8pt;" align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="https://otexts.com/fpp2/components.html"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Componentes de séries temporais</span></a></li>
                                        <li style=" font-size:8pt;" align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="https://peerj.com/preprints/3190/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Artigo sobre o fbprophet</span></a></li></ul></body></html>''',

    'De onde vêm os dados?' : '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                                p, li { white-space: pre-wrap; }
                                </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;">
                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">De onde vêm os dados?</span></p>
                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Os dados utilizados pelo programa vêm do </span><a href="https://covid.saude.gov.br/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Ministério da Saúde</span></a><span style=" font-size:12pt;"> e do </span><a href="https://brasil.io/covid19/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Brasil.io</span></a><span style=" font-size:12pt;">. Foram escolhidas duas fontes porque, em alguns momentos durante o desenvolvimento, os dados advindos do Ministério da Saúde não abrangiam o período completo do qual se tem dados sobre a Covid-19.</span></p>
                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Desta forma, caso isso ocorra novamente, o usuário ainda conseguirá realizar as análises desejadas.</span></p></body></html>''',

    'Como os dados são organizados no programa?' : '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                                    <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                                                    p, li { white-space: pre-wrap; }
                                                    </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;">
                                                    <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">Como os dados são organizados no programa?</span></p>
                                                    <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Por ora, os dados a respeito da Covid-19 são lidos de arquivos .csv advindos do </span><a href="https://covid.saude.gov.br/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Ministério da Saúde</span></a><span style=" font-size:12pt;"> e do </span><a href="https://brasil.io/covid19/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Brasil.io</span></a><span style=" font-size:12pt;">. Cada um deste conjuntos de dados é armazenado em um DataFrame da biblioteca </span><a href="https://pandas.pydata.org/"><span style=" font-size:12pt; font-style:italic; text-decoration: underline; color:#0000ff;">pandas</span></a><span style=" font-size:12pt;">, os quais fazem parte de um objeto da classe CovidData, presente no arquivo </span><span style=" font-size:12pt; font-style:italic;">main.py.</span></p>
                                                    <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">A classe CovidData contém os métodos que leem os arquivos </span><span style=" font-size:12pt; font-style:italic;">.csv</span><span style=" font-size:12pt;">, filtram dados, plotam gráficos e realizam previsões.</span></p></body></html>''',

    'Como o programa atualiza os dados?' : '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                            <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                                            p, li { white-space: pre-wrap; }
                                            </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;">
                                            <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">Como o programa atualiza os dados?</span></p>
                                            <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; text-decoration: underline;">Dados do Ministério da Saúde</span></p>
                                            <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Para obter os dados do </span><a href="https://covid.saude.gov.br/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Ministério da Saúde</span></a><span style=" font-size:12pt;">, o programa utiliza a biblioteca selenium para controle de um webdriver do Google Chrome, o qual acessa o site do Ministério e clica no botão de download dos dados. Isso é necessário porque não há um link direto ao arquivo no código HTML da página.</span></p>
                                            <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Em seguida, o programa transfere o arquivo baixado para sua própria pasta. Porém, o formato original é </span><span style=" font-size:12pt; font-style:italic;">.xlsx, </span><span style=" font-size:12pt;">o qual é convertido via um script em </span><span style=" font-size:12pt; font-style:italic;">Visual Basic</span><span style=" font-size:12pt;"> para </span><span style=" font-size:12pt; font-style:italic;">.csv</span><span style=" font-size:12pt;">. Isso é feito porque o método </span><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html"><span style=" font-size:12pt; font-style:italic; text-decoration: underline; color:#0000ff;">read_excel</span></a><span style=" font-size:12pt;"> do </span><a href="https://pandas.pydata.org/"><span style=" font-size:12pt; font-style:italic; text-decoration: underline; color:#0000ff;">pandas</span></a><span style=" font-size:12pt;"> consumia um tempo consideravelmente longo, sendo mais rápido converter e ler o arquivo </span><span style=" font-size:12pt; font-style:italic;">.csv</span><span style=" font-size:12pt;">.</span></p>
                                            <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; text-decoration: underline;">Dados do Brasil.io</span></p>
                                            <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Há uma facilidade maior em obter os dados do </span><a href="https://brasil.io/covid19/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Brasil.io</span></a><span style=" font-size:12pt;">, uma vez que é possível acessar o link direto ao arquivo. Este é baixado como um </span><span style=" font-size:12pt; font-style:italic;">.csv</span><span style=" font-size:12pt;"> compactado (formato </span><span style=" font-size:12pt; font-style:italic;">.csv.gz</span><span style=" font-size:12pt;">), o qual é descompactado com a biblioteca </span><span style=" font-size:12pt; font-style:italic;">gzip</span><span style=" font-size:12pt;"> do Python e lido.</span></p></body></html>''',

    'Como a interface gráfica foi criada?' : '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                                <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                                                p, li { white-space: pre-wrap; }
                                                </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;">
                                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">Como a interface gráfica foi criada?</span></p>
                                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">A interface gráfica do programa é baseada na biblioteca </span><a href="https://pypi.org/project/PyQt5/"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">PyQt5</span></a><span style=" font-size:12pt;"> e foi criada e organizada utilizando o </span><a href="https://doc.qt.io/qt-5/qtdesigner-manual.html"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Qt Designer</span></a><span style=" font-size:12pt;">, facilitando, assim, sua elaboração.</span></p>
                                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">O Qt Designer gera arquivos no formato </span><span style=" font-size:12pt; font-style:italic;">.ui</span><span style=" font-size:12pt;">, o qual pode ser convertido para formato </span><span style=" font-size:12pt; font-style:italic;">.py</span><span style=" font-size:12pt;"> através da biblioteca </span><a href="https://pypi.org/project/pyuic5-tool/"><span style=" font-size:12pt; font-style:italic; text-decoration: underline; color:#0000ff;">pyuic5</span></a><span style=" font-size:12pt;">.</span></p></body></html>''',

    'O que significam as "Opções" do Prophet?' : '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                                    <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                                                    p, li { white-space: pre-wrap; }
                                                    </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;">
                                                    <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">O que significam as &quot;Opções&quot; do Prophet?</span></p>
                                                    <ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;"><li align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Seasonality Prior Scale</span></a><span style=" font-size:12pt;">: representa a frequência das oscilações sazonais dos dados. Quanto maior for esse valor, maior a frequência assumida pelo modelo.</span></li>
                                                    <li align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="https://facebook.github.io/prophet/docs/trend_changepoints.html#adjusting-trend-flexibility"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Changepoint Prior Scale</span></a><span style=" font-size:12pt; text-decoration: underline;">:</span><span style=" font-family:'Arial,sans-serif'; font-size:12pt;"> denota a flexibilidade que o modelo tem para alterar as tendências futuras. Quanto maior o valor, mais flexível se torna o modelo</span><span style=" font-family:'Calibri,sans-serif'; font-size:12pt;">.</span></li>
                                                    <li align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html"><span style=" font-size:12pt; text-decoration: underline; color:#0000ff;">Holidays Prior Scale</span></a><span style=" font-size:12pt; text-decoration: underline;">:</span><span style=" font-family:'Arial,sans-serif'; font-size:12pt;"> similar ao anterior, mas relativo a feriados.</span></li></ul></body></html>''',
    
    'Por que o programa não encontra o local que digitei?' : '''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                                                <html><head><meta name="qrichtext" content="1" /><style type="text/css">
                                                                p, li { white-space: pre-wrap; }
                                                                </style></head><body style=" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;">
                                                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; text-decoration: underline;">Por que o programa não encontra o local que digitei?</span></p>
                                                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; text-decoration: underline;">Dados do Ministério da Saúde:</span></p>
                                                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Os dados do Ministério da Saúde estão organizados em Região, Estado e Cidade. Se o programa não encontrou o local digitado, é possível que seja necessário especificar a região. Além disso, o conjunto de dados conta com uma região &quot;Brasil&quot; para dados do país todo. Com esta região, não há a seleção de estados nem cidades, podendo ocasionar um erro caso estes sejam especificados. Para especificar um estado específico, em alguns casos é necessário preencher uma região.</span></p>
                                                                <p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; text-decoration: underline;">Dados do Brasil.io:</span><span style=" font-size:12pt;"> no caso dos dados do Brasil.io, não há opções de região, sendo possível digitar apenas os dados de estado e cidade.</span></p>
                                                                <p align="justify" style="-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p></body></html>'''
}